### ISSUE TITLE
simulateJava fails without error on macOS Catalina

### ISSUE THREAD

**Issue by cpostbitbuckets** [wpilibsuite/GradleRIO#413]
I created a new empty command robot project and executed `./gradlew simulateJava`. 

```bash
/UnitTestBot$ ./gradlew simulateJava
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :simulateJava
Program Output logfile: /UnitTestBot/build/stdout/simulateJava.log
Simulation Launched! PID: 39850 (written to /UnitTestBot/build/pids/simulateJava.pid)

BUILD SUCCESSFUL in 5s
5 actionable tasks: 3 executed, 2 up-to-date
```

I launched the build script directly and it showed a native library load error:

```bash
/UnitTestBot$ ./build/gradlerio_simulateJava.sh 
java.io.IOException: wpiHaljni could not be loaded from path or an embedded resource.
	attempted to load for platform /osx/x86-64/
Last Load Error: 
/UnitTestBot/build/tmp/jniExtractDir/libwpiHaljni.dylib: dlopen(/UnitTestBot/build/tmp/jniExtractDir/libwpiHaljni.dylib, 1): Library not loaded: libwpiHal.dylib
  Referenced from: /UnitTestBot/build/tmp/jniExtractDir/libwpiHaljni.dylib
  Reason: image not found

	at edu.wpi.first.wpiutil.RuntimeLoader.loadLibrary(RuntimeLoader.java:84)
	at edu.wpi.first.hal.JNIWrapper.<clinit>(JNIWrapper.java:38)
	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:316)
	at frc.robot.Main.main(Main.java:27)
```

If I update the launch script to include a DYLD_LIBRARY_PATH environment var, it works.

```bash
export DYLD_LIBRARY_PATH=/UnitTestBot/build/tmp/jniExtractDir
```

I'm not sure why DYLD_FALLBACK_LIBRARY_PATH doesn't work, but it's not finding the sim native libraries.

**Comment by PeterJohnson** [comment]
Fixed by #455.
